/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const FavoritesIndexLazyImport = createFileRoute('/favorites/')()
const PokemonIdLazyImport = createFileRoute('/pokemon/$id')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FavoritesIndexLazyRoute = FavoritesIndexLazyImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/favorites/index.lazy').then((d) => d.Route),
)

const PokemonIdLazyRoute = PokemonIdLazyImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pokemon/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon/$id': typeof PokemonIdLazyRoute
  '/favorites': typeof FavoritesIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemon/$id': typeof PokemonIdLazyRoute
  '/favorites': typeof FavoritesIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokemon/$id': typeof PokemonIdLazyRoute
  '/favorites/': typeof FavoritesIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemon/$id' | '/favorites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon/$id' | '/favorites'
  id: '__root__' | '/' | '/pokemon/$id' | '/favorites/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonIdLazyRoute: typeof PokemonIdLazyRoute
  FavoritesIndexLazyRoute: typeof FavoritesIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonIdLazyRoute: PokemonIdLazyRoute,
  FavoritesIndexLazyRoute: FavoritesIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemon/$id",
        "/favorites/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemon/$id": {
      "filePath": "pokemon/$id.lazy.tsx"
    },
    "/favorites/": {
      "filePath": "favorites/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
